#!/usr/bin/env python

data404='404 NOT FOUND\n'
data500='500 INTERNAL SERVER ERROR\n'
DEBUG=False

#port and ip

import sys
import re

def set_port(p):
    global port
    try:
        port = int(p)
    except ValueError:
        raise Exception("the port arguement should be a number")
    if port > 65535 or port < 1:
        raise Exception("the port should between 1 and 65535")

def set_ip(i):
    global ip
    ip = i
    m = re.match(r'^([01]?\d\d?|2[0-4]\d|25[0-5])\.([01]?\d\d?|2[0-4]\d|25[0-5])\.([01]?\d\d?|2[0-4]\d|25[0-5])\.([01]?\d\d?|2[0-4]\d|25[0-5])$',ip)
    if not m:
        raise Exception("invalid ip")
    

if len(sys.argv) is 1:
    port = 8000
    ip = "0.0.0.0"
elif len(sys.argv) is 2:
    set_port(sys.argv[1])
    ip = "0.0.0.0"
else:
    set_port(sys.argv[2])
    set_ip(sys.argv[1])

#evaluate

import subprocess

def eva(src):
    def evenif(tail):
        sum=0
        while data[tail] is '?':
            tail = tail -1
            sum = sum + 1
        return sum % 2 is 0
    def runer(pre):
        pre = pre.replace('??','?')
        sp1 = pre.find(' ')
        sp2 = pre.find('\n')
        if DEBUG:
            print pre
            print sp1
            print sp2
        if sp1 is -1 and sp2 is -1:
            raise Exception('invalid format')
        if sp1 is -1:
            sp = sp2
        elif sp2 is -1:
            sp = sp1
        else:
            sp = sp1 if sp1 < sp2 else sp2
        evaler = pre[:sp]
        script = pre[sp+1:]
        if DEBUG:
            print sp
            print evaler
            print script
        pro = subprocess.Popen(evaler,stdin=subprocess.PIPE,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
        pro.stdin.write("%s\n\n"%script)
        anser = pro.communicate()
        if DEBUG:
            print anser
        ans = anser[0]
        if anser[1] is not '':
            raise Exception('script error')
            print anser[1]
        return ans.replace('?','??')
    data = src
    while data.find('<?') is not -1:
        head = data.find('<?')
        tail = data.find('?>',head+1)
        while evenif(tail):
            tail = data.find('?>',tail+1)
            if tail is -1:
                raise Exception('invalid format')
        data = '%s%s%s'%(data[:head],runer(data[head+2:tail]),data[tail+2:])
    return data.replace('??','?')
    
#response

import mimetypes
import posixpath

maps = mimetypes.types_map.copy()
maps.update({'':'application/octet-stream'})

def app(environ, start_response):
    method = environ["REQUEST_METHOD"]
    path = environ["PATH_INFO"]
    query = environ["QUERY_STRING"]
    if DEBUG:
        print path
    if path[-4:] == '.ral':
        try:
            file = open('.%s'%path, 'r')
            if DEBUG:
                print '.%s'%path
            src = file.read()
            file.close()
            try:
                data = eva(src)
                start_response('200 OK',[('Content-Type','text/html')])
                return [data]
            except Exception, e:
                print e
                start_response('500 INTERNAL SERVER ERROR',[('Content-Type','text/html')])
                return [data500]
        except IOError:
            start_response('404 NOT FOUND',[('Content-Type','text/html')])
            return [data404]
    elif path[-5:] == '.html':
        try:
            file = open('.%s'%path, 'r')
            if DEBUG:
                print '.%s'%path
            data = file.read()
            file.close()
            start_response('200 OK',[('Content-Type','text/html')])
            return [data]
        except IOError:
            start_response('404 NOT FOUND',[('Content-Type','text/html')])
            return [data404]
    elif path[-1] == '/':
        try:
            file = open('.%sindex.ral'%path,'r')
            if DEBUG:
                print '.%sindex.ral'%path
            src = file.read()
            file.close()
            try:
                data = eva(src)
                start_response('200 OK',[('Content-Type','text/html')])
                return [data]
            except Exception, e:
                print e
                start_response('500 INTERNAL SERVER ERROR',[('Content-Type','text/html')])
                return [data500]
        except IOError:
            try:
                file = open('.%sindex.html'%path,'r')
                if DEBUG:
                    print '.%sindex.html'%path
                data = file.read()
                file.close()
                start_response('200 OK',[('Content-Type','text/html')])
                return [data]
            except IOError:
                start_response('404 NOT FOUND',[('Content-Type','text/html')])
                return [data404]
    else:
        try:
            file = open('.%s'%path,'r')
            ext = posixpath.splitext(path)[1]
            if ext in maps:
                types = maps[ext]
            else:
                types = maps['']
            data = file.read()
            file.close()
            start_response('200 OK',[('Content-Type',types)])
            return data
        except IOError:
            start_response('404 NOT FOUND',[('Content-Type','test/html')])
            return [data404]

#server

from wsgiref.simple_server import make_server

httpd = make_server(ip, port, app)
print "starting server in %s:%d" % (ip,port)
httpd.serve_forever()
